version = 1

[install]
  [install.age]
    pkg-path = 'age'

  [install.gnupg]
    pkg-path = 'gnupg'

  [install.keychain]
    pkg-path = 'keychain'

  [install.pass]
    pkg-path = 'pass'

  [install.sops]
    pkg-path = 'sops'

  [install.ssh-to-age]
    pkg-path = 'ssh-to-age'

[options]

[profile]
  common = """
    GITHUB_SIGNING_KEYFILE="$HOME"/.ssh/keys.d/github-signing
    if [[ -r "$GITHUB_SIGNING_KEYFILE" ]]; then
      set -a
      SOPS_AGE_KEY=$( ssh-to-age -private-key < "$GITHUB_SIGNING_KEYFILE" )
      set +a
    else
      echo no signing key
    fi
  """
