# Source: kubernetes-replicator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-replicator
  namespace: kube-system
  labels:
    helm.sh/chart: kubernetes-replicator-2.12.2
    app.kubernetes.io/name: kubernetes-replicator
    app.kubernetes.io/instance: kubernetes-replicator
    app.kubernetes.io/version: "v2.12.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-replicator
      app.kubernetes.io/instance: kubernetes-replicator
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      labels:
        app.kubernetes.io/name: kubernetes-replicator
        app.kubernetes.io/instance: kubernetes-replicator
    spec:
      serviceAccountName: kubernetes-replicator
      automountServiceAccountToken: true
      securityContext: {}
      containers:
      - name: kubernetes-replicator
        securityContext: {}
        image: "quay.io/mittwald/kubernetes-replicator:v2.12.2"
        imagePullPolicy: Always
        args:
        - -replicate-secrets=true
        - -replicate-configmaps=true
        - -replicate-roles=true
        - -replicate-role-bindings=true
        - -replicate-service-accounts=true
        ports:
        - name: health
          containerPort: 9102
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 15m
            memory: 64Mi
