apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 0-ghcr-secret.yaml
  - 0-packagerevs.yaml
  - 0-packagevariants.yaml
  - 0-packagevariantsets.yaml
  - 0-repositories.yaml
  - 1-namespace.yaml
  - 2-function-runner.yaml
  - 2b-fn-default-serviceaccount.yaml
  - 3-porch-server.yaml
  - 4-apiservice.yaml
  - 5-rbac.yaml
  - 6-rbac-bind.yaml
  - 7-auth-reader.yaml
  - 8-auth-delegator.yaml
  - 9-controllers.yaml
  - 9-porch-controller-clusterrole.yaml
  - 9-porch-controller-packagevariants-clusterrole.yaml
  - 9-porch-controller-packagevariants-clusterrolebinding.yaml
  - 9-porch-controller-packagevariantsets-clusterrole.yaml
  - 9-porch-controller-packagevariantsets-clusterrolebinding.yaml
  - package-context.yaml
  - porch-setters.yaml
