version = 1

[install]
  [install.xdg-ninja]
    pkg-group = 'xdg'
    pkg-path = 'xdg-ninja'

  [install.xdg-user-dirs]
    pkg-group = 'xdg'
    pkg-path = 'xdg-user-dirs'

  [install.xdg-utils]
    pkg-group = 'xdg'
    pkg-path = 'xdg-utils'

[options]

[profile]
  common = """
    set -a
    
    XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
    XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
    XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
    XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}
    XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-$HOME/.xdg}
    
    set +a
  """
