version = 1

[install]
  [install.lima]
    pkg-group = 'lima'
    pkg-path = 'lima'

  [install.vmnet]
    pkg-group = 'lima'
    pkg-path = 'darwin.apple_sdk.frameworks.vmnet'

[options]
  systems = ['aarch64-darwin', 'x86_64-darwin']
