version = 1

[install]
  [install.dasel]
    pkg-group = 'manifest-tools-yaml-tools'
    pkg-path = 'dasel'
    version = '^2.8.1'

  [install.yq-go]
    pkg-group = 'manifest-tools-yaml-tools'
    pkg-path = 'yq-go'

[options]
  systems = ['aarch64-darwin', 'aarch64-linux']
