apiVersion: v1
kind: ConfigMap
metadata:
  name: http-resolver-config
  labels:
    app.kubernetes.io/component: resolvers
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
data:
  # The maximum amount of time the http resolver will wait for a response from the server.
  fetch-timeout: "1m"
