version = 1

[include]
  [[include.environments]]
    dir = '/var/lib/git/nxmatic/fleet-manifests/flox/xdg'

  [[include.environments]]
    dir = '/var/lib/git/nxmatic/fleet-manifests/flox/keyhole'

[install]
  [install.direnv]
    pkg-path = 'direnv'

  [install.linux-builder]
    pkg-path = 'darwin.linux-builder'
    systems = ['aarch64-darwin']

  [install.lldpd]
    pkg-path = 'lldpd'

[options]
  systems = ['aarch64-darwin', 'aarch64-linux']
