version = 1

[include]
  [[include.environments]]
    dir = '/var/lib/git/nxmatic/fleet/flox/xdg'

  [[include.environments]]
    dir = '/var/lib/git/nxmatic/fleet/flox/keyhole'

[install]
  [install.direnv]
    pkg-group = 'home'
    pkg-path = 'direnv'

  [install.linux-builder]
    pkg-group = 'home'
    pkg-path = 'darwin.linux-builder'
    systems = ['aarch64-darwin']

  [install.lldpd]
    pkg-group = 'home'
    pkg-path = 'lldpd'

[options]
  systems = ['aarch64-darwin', 'aarch64-linux']
