apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium
  - ./flux-instance
  - ./flux-operator
  - ./porch
  - ./porch-resources
  - ./replicator
  - ./tekton-pipelines
  - ./traefik
